params:
  temperature: 0.5
sim:
  version: 'swap'
  fill_blank: True
  stochastic: True
  mode: 'api' #'gpu'
model:
  model_name: "meta-llama/Llama-3.3-70B-Instruct"
  shorthand: "llama33_70B"
  API_TOKEN: ''
  sys_prompt_is_avail: True
  chat_template_is_avail: True
  quantized: True